# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/chudy/projekty/vala/filemgr

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/chudy/projekty/vala/filemgr

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/chudy/projekty/vala/filemgr/CMakeFiles /home/chudy/projekty/vala/filemgr/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/chudy/projekty/vala/filemgr/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named filemgr

# Build rule for target.
filemgr: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 filemgr
.PHONY : filemgr

# fast build rule for target.
filemgr/fast:
	$(MAKE) -f CMakeFiles/filemgr.dir/build.make CMakeFiles/filemgr.dir/build
.PHONY : filemgr/fast

src/directory_controller.o: src/directory_controller.c.o
.PHONY : src/directory_controller.o

# target to build an object file
src/directory_controller.c.o:
	$(MAKE) -f CMakeFiles/filemgr.dir/build.make CMakeFiles/filemgr.dir/src/directory_controller.c.o
.PHONY : src/directory_controller.c.o

src/directory_controller.i: src/directory_controller.c.i
.PHONY : src/directory_controller.i

# target to preprocess a source file
src/directory_controller.c.i:
	$(MAKE) -f CMakeFiles/filemgr.dir/build.make CMakeFiles/filemgr.dir/src/directory_controller.c.i
.PHONY : src/directory_controller.c.i

src/directory_controller.s: src/directory_controller.c.s
.PHONY : src/directory_controller.s

# target to generate assembly for a file
src/directory_controller.c.s:
	$(MAKE) -f CMakeFiles/filemgr.dir/build.make CMakeFiles/filemgr.dir/src/directory_controller.c.s
.PHONY : src/directory_controller.c.s

src/directory_view.o: src/directory_view.c.o
.PHONY : src/directory_view.o

# target to build an object file
src/directory_view.c.o:
	$(MAKE) -f CMakeFiles/filemgr.dir/build.make CMakeFiles/filemgr.dir/src/directory_view.c.o
.PHONY : src/directory_view.c.o

src/directory_view.i: src/directory_view.c.i
.PHONY : src/directory_view.i

# target to preprocess a source file
src/directory_view.c.i:
	$(MAKE) -f CMakeFiles/filemgr.dir/build.make CMakeFiles/filemgr.dir/src/directory_view.c.i
.PHONY : src/directory_view.c.i

src/directory_view.s: src/directory_view.c.s
.PHONY : src/directory_view.s

# target to generate assembly for a file
src/directory_view.c.s:
	$(MAKE) -f CMakeFiles/filemgr.dir/build.make CMakeFiles/filemgr.dir/src/directory_view.c.s
.PHONY : src/directory_view.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) -f CMakeFiles/filemgr.dir/build.make CMakeFiles/filemgr.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) -f CMakeFiles/filemgr.dir/build.make CMakeFiles/filemgr.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) -f CMakeFiles/filemgr.dir/build.make CMakeFiles/filemgr.dir/src/main.c.s
.PHONY : src/main.c.s

src/main_window.o: src/main_window.c.o
.PHONY : src/main_window.o

# target to build an object file
src/main_window.c.o:
	$(MAKE) -f CMakeFiles/filemgr.dir/build.make CMakeFiles/filemgr.dir/src/main_window.c.o
.PHONY : src/main_window.c.o

src/main_window.i: src/main_window.c.i
.PHONY : src/main_window.i

# target to preprocess a source file
src/main_window.c.i:
	$(MAKE) -f CMakeFiles/filemgr.dir/build.make CMakeFiles/filemgr.dir/src/main_window.c.i
.PHONY : src/main_window.c.i

src/main_window.s: src/main_window.c.s
.PHONY : src/main_window.s

# target to generate assembly for a file
src/main_window.c.s:
	$(MAKE) -f CMakeFiles/filemgr.dir/build.make CMakeFiles/filemgr.dir/src/main_window.c.s
.PHONY : src/main_window.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... filemgr"
	@echo "... rebuild_cache"
	@echo "... src/directory_controller.o"
	@echo "... src/directory_controller.i"
	@echo "... src/directory_controller.s"
	@echo "... src/directory_view.o"
	@echo "... src/directory_view.i"
	@echo "... src/directory_view.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/main_window.o"
	@echo "... src/main_window.i"
	@echo "... src/main_window.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

